export const en = {
  dashboard: 'Dashboard',
  invoice: 'Invoice',
  expanse: 'Expanse',
  report: 'Report',
  profile: 'Profile',
  logout: 'Logout',
  paymentMethod: 'Payment method',
  employeeList: 'Employee list',
  customerList: 'Customer list',
  menu: 'Menu',
  receipt: 'Receipt',
  transaction: 'Transaction',
  transactionDetail: 'Transaction detail',
  account: 'Account',
  balance: 'Balance',
  payment: 'Payment',
  customer: 'Customer',
  phone: 'Phone',
  category: 'Payment Method',
};

export const vi = {
  dashboard: 'Trang chủ',
  invoice: 'Hoá đơn',
  expanse: 'Chi phí',
  report: 'Báo cáo',
  profile: 'Thông tin cá nhân',
  logout: 'Đăng xuất',
  paymentMethod: 'Phương thức thanh toán',
  employeeList: 'Danh sách nhân viên',
  customerList: 'Danh sách khách hàng',
  menu: 'Danh mục',
  receipt: 'Biên lai',
  transaction: 'Giao dịch',
  transactionDetail: 'Chi tiết giao dịch',
  account: 'Tài khoản',
  balance: 'Bảng cân đối',
  payment: 'Thanh toán',
  customer: 'Khách hàng',
  phone: 'Số điện thoại',
  category: 'Phương thức thanh toán',
};
