export const en = {
  local: 'en-EN',

  dashboard: 'Dashboard',
  profile: 'Profile',
  login: 'Login',
  signup: 'Sign up',
  logout: 'Logout',

  invoice: 'Invoice',
  invoiceAddition: 'Add invoice',
  invoiceDetail: 'Invoice detail',
  invoiceProductAddition: 'Add product',
  invoiceProductUpdate: 'Update product',
  invoiceScanner: 'Invoice barcode scanner',
  paymentAddition: 'Add payment',

  receipt: 'Receipt',
  receiptDetail: 'Receipt detail',
  receiptAddition: 'Add receipt',

  paymentMethod: 'Payment method',
  paymentMethodAddition: 'Add payment method',

  employee: 'Employee',
  employeeAddition: 'Add employee',
  employeeManagement: 'Employee management',

  customer: 'Customer',
  customerAddition: 'Add customer',
  customerManagement: 'Customer management',
  menu: 'Menu',

  transaction: 'Transaction',
  transactionDetail: 'Transaction detail',
  transactionAddition: 'Add transaction',

  search: 'Search',
  account: 'Account',
  accountAddition: 'Add account',

  balance: 'Balance',
  payment: 'Payment',

  // ADD FIELD
  username: 'Username',
  password: 'Password',
  repassword: 'Repassword',
  fullname: 'Fullname',
  role: 'Role',
  email: 'Email',
  phone: 'Phone',
  name: 'Name',
  quantity: 'Quantity',
  unitPrice: 'Unit Price',
  detail: 'Description',
  staff: 'Staff',
  accountant: 'Accountant',
  manager: 'Manager',
  address: 'Address',
  purchasedInvoice: 'Purchased invoice',
  selledInvoice: 'Selled invoice',
  product: 'Product',
  cost: 'Cost',
  totalCost: 'Total cost',
  paymentIn: 'Received',
  paymentOut: 'Spent',
  amountMoney: 'Ammount of money',
  description: 'Description',
  company: 'Company',
  purchase: 'Purchase',
  sale: 'Sale',
  paid: 'Paid',
  unpaid: 'Unpaid',
  addedBy: 'Added by',
  receiptRecoredAsTransaction: 'Recorded as a transaction',
  receiptNotRecoredAsTransaction: 'Not record as a transaction yet',
  receiptVoucher: 'Receipt voucher',
  paymentVoucher: 'Payment Voucher',

  // ADVANCED FILTER GROUP
  advancedFilter: 'Advanced filter',
  from: 'From',
  to: 'To',
  doFilter: 'Filter',

  // ACTION GROUP
  actionSave: 'Save',
  actionUpdate: 'Update',
  actionEdit: 'Edit',
  actionRemove: 'Remove',
  actionHide: 'Hide',
  actionShowPayment: 'Show recorded payments',
  actionAddProduct: '+ Add more product',
  actionAddPayment: '+ Add more payment',
  actionChoosePayment: 'Choose payment',
  actionChooseCustomer: 'Choose customer',
  actionChoosePaymentMethod: 'Choose payment method',

  // MESSAGE GROUP
  messageEmpty: 'There is no',
  messageUnsuccess: 'Unsuccessful',
  messageAddFail: 'Add failed, please check again.',
  messageUpdateFail: 'Update failed, please check again.',
  messageDeleteFail: 'Delete failed, please try again later.',
  messageDeleteSuccess: 'Delete successfully',
  messageWP: 'Your repassword is not match',
  messageForgetPassword: 'Forget your password',
  messageHaveNoAccount: `Don't have an account?`,
  messageNoAccessCamera: 'Cannot access to Camera',
  messageScanInvoice: 'Take a photo of your invoice',
  messageCanNotGetInvoiceId: 'Cannot get invoice has ID:',
  messageGuildToScan:
    'Place the camera where the barcode is on the invoice and adjust the phone so that the barcode is right in the camera on the screen',

  // LANGUAGE
  english: 'English',
  vietnamese: 'Vietnamese',
};

export const vi = {
  local: 'vi-VN',

  dashboard: 'Trang chủ',
  profile: 'Thông tin cá nhân',
  login: 'Đăng nhập',
  signup: 'Đăng ký',
  logout: 'Đăng xuất',

  invoice: 'Hoá đơn',
  invoiceAddition: 'Thêm hoá đơn',
  invoiceDetail: 'Chi tiết hóa đơn',
  invoiceProductAddition: 'Thêm sản phẩm',
  invoiceProductUpdate: 'Cập nhật sản phẩm',
  invoiceScanner: 'Quét mã vạch hóa đơn',
  paymentAddition: 'Thêm khoản thanh toán',

  receipt: 'Biên lai',
  receiptDetail: 'Chi tiết biên lai',
  receiptAddition: 'Thêm biên lai',

  paymentMethod: 'Phương thức thanh toán',
  paymentMethodAddition: 'Thêm phương thức thanh toán',

  employee: 'Nhân viên',
  employeeAddition: 'Thêm nhân viên',
  employeeManagement: 'Quản lý nhân viên',

  customer: 'Khách hàng',
  customerAddition: 'Thêm khách hàng',
  customerManagement: 'Quản lý khách hàng',
  menu: 'Danh mục',

  transaction: 'Giao dịch',
  transactionDetail: 'Chi tiết giao dịch',
  transactionAddition: 'Thêm giao dịch',

  search: 'Tìm kiếm',
  account: 'Tài khoản',
  accountAddition: 'Thêm tài khoản',

  balance: 'Bảng cân đối',
  payment: 'Khoản thanh toán',

  // ADD FIELD
  username: 'Tên đăng nhập',
  password: 'Mật khẩu',
  repassword: 'Xác nhận mật khẩu',
  fullname: 'Họ và tên',
  role: 'Vai trò',
  email: 'Thư điện tử',
  phone: 'Số điện thoại',
  name: 'Tên',
  quantity: 'Số lượng',
  unitPrice: 'Đơn giá',
  detail: 'Mô tả chi tiết',
  staff: 'Nhân viên',
  accountant: 'Kế toán',
  manager: 'Quản lý',
  address: 'Địa chỉ',
  purchasedInvoice: 'Hóa đơn nhập hàng',
  selledInvoice: 'Hóa đơn bán hàng',
  product: 'Sản phẩm',
  cost: 'Thành tiền',
  totalCost: 'Tổng tiền',
  paymentIn: 'Nhận vào',
  paymentOut: 'Chi ra',
  amountMoney: 'Số tiền',
  description: 'Mô tả',
  company: 'Công ty',
  paid: 'Đã thanh toán',
  unpaid: 'Chưa thanh toán',
  purchase: 'Nhập hàng',
  sale: 'Bán hàng',
  addedBy: 'Đã thêm bởi',
  receiptRecoredAsTransaction: 'Đã ghi nhận phiên giao dịch',
  receiptNotRecoredAsTransaction: 'Chưa lưu thành phiên giao dịch',
  receiptVoucher: 'Phiếu thu',
  paymentVoucher: 'Phiếu chi',

  // ADVANCED FILTER GROUP
  advancedFilter: 'Bộ lọc nâng cao',
  from: 'Từ',
  to: 'Đến',
  doFilter: 'Lọc',

  // ACTION GROUP
  actionSave: 'Lưu',
  actionUpdate: 'Cập nhật',
  actionEdit: 'Sửa',
  actionRemove: 'Xóa',
  actionHide: 'Ẩn',
  actionShowPayment: 'Hiện các khoản đã thanh toán',
  actionAddProduct: '+ Thêm sản phẩm',
  actionAddPayment: '+ Thêm khoản thanh toán',
  actionChoosePayment: 'Chọn khoản thanh toán',
  actionChooseCustomer: 'Chọn khách hàng',
  actionChoosePaymentMethod: 'Chọn phương thức thanh toán',

  // MESSAGE GROUP
  messageEmpty: 'Hiện chưa có',
  messageUnsuccess: 'Không thành công',
  messageNotAllowEmpty: 'Không nhận dữ liệu rỗng',
  messageAddFail: 'Thêm không thành công, vui lòng kiểm tra lại.',
  messageUpdateFail: 'Cập nhật không thành công, vui lòng kiểm tra lại.',
  messageDeleteFail: 'Xóa không thành công, vui lòng thử lại sau.',
  messageDeleteSuccess: 'Xoá thành công',
  messageWP: 'Xác nhận mật khẩu không khớp',
  messageForgetPassword: 'Quên mật khẩu',
  messageHaveNoAccount: `Chưa có tài khoản?`,
  messageNoAccessCamera: 'Không thể kết nối với Camera',
  messageScanInvoice: 'Chụp hình hoá đơn của bạn',
  messageCanNotGetInvoiceId: 'Không thể tìm thấy hóa đơn có ID:',
  messageGuildToScan:
    'Đưa camera lại nơi có mã vạch trên hóa đơn và điều chỉnh điện thoại sao cho mã vạch nằm đúng trong camera trên màn hình',

  // LANGUAGE
  english: 'Tiếng Anh',
  vietnamese: 'Tiếng Việt',
};

export const localizations = {
  English: 'en',
  Vietnamese: 'vi',
};
